from django.urls import path
from AppCoder import views

urlpatterns = [
    path("", views.inicio, name='Inicio'),
    path("Adopciones/", views.Adopciones,name='¿Queres dar en Adopcion?'),
    path("adopcionApi/", views.adopcionApi ), 
    path("Encontrados/", views.Encontradooos, name='Encontre' ),
    path("Provisorio/", views.Provisoriooos, name= 'Provi' ),
    path("busquedaAdopcion/", views.buscaradopcion, name='Buscar'),
    path("buscar/", views.buscar),
    path("leeradopcion/" , views.leer_adopcion),
    path("crearadopcion/",views.crear_adopcion),
    path("editaradopcion/",views.editar_adopcion),
    path("eliminaradopcion/",views.eliminar_adopcion),
    path("adopciones/list/",views.AdopcionesList.as_view(), name='List'),
    path("adopciones/create/", views.AdopcionesCreate.as_view(),name='New'),
    path("adopciones/edit/<pk>", views.AdopcionesEdit.as_view(),name='Edit'),
    path("adopciones/detail/<pk>", views.AdopcionesDetail.as_view(),name='Detail'),
    path("adopciones/delete/<pk>", views.AdopcionesDelete.as_view(),name='Delete'),
    path("provisoriosApi/", views.provisoriosApi),
    path("busquedaProviosorio/", views.buscarprovisorio, name= 'buscarProvi'),
    path("buscarP/", views.buscarP),
    path("leerprovi/" , views.leer_provisorio),
    path("crearprovi/",views.crear_provisorio),
    path("editarprovi/",views.editar_provisorio),
    path("eliminarprovi/",views.eliminar_provirosio),
    path("provisorios/list/",views.ProvisoriosList.as_view(), name='ListP'),
    path("provisorios/create/", views.ProvisoriosCreate.as_view(),name='NewP'),
    path("provisorios/edit/<pk>", views.ProvisoriosEdit.as_view(),name='EditP'),
    path("provisorios/detail/<pk>", views.ProvisoriosDetail.as_view(),name='DetailP'),
    path("provisorios/delete/<pk>", views.ProvisoriosDelete.as_view(),name='DeleteP'),
    path("encontradosApi/", views.encontradosApi,),
    path("busquedaEncontrado/", views.buscarencontrados, name= 'buscarEncontrado'),
    path("buscarE/", views.buscarE),
    path("leerencontrado/" , views.leer_encontrado),
    path("crearencontrado/",views.crear_encontrado),
    path("editarencontrado/",views.editar_encontrado),
    path("eliminarencontrado/",views.eliminar_encontrado),
    path("encontrado/create/",views.EncontradoCreacion.as_view(),name='NewE'),
    path("encontrado/list/",views.EncontradoList.as_view(),name='ListE'),
    path("encontrado/edit/<pk>",views.EncontradoEdit.as_view(),name='EditE'),
    path("encontrado/detail/<pk>",views.EncontradoDetail.as_view(),name='DetailE'),
    path("encontrado/delete/<pk>",views.EncontradoDelete.as_view(),name='DeleteE'),
    path("historia", views.historia, name = 'historia'),
    path("contacto", views.contacto, name = 'contacto'),
    path("quien", views.Quien, name = 'quien'),
    path("privacidad", views.Privacidad, name = 'privacidad'),
]
   