# Generated by Django 4.1.3 on 2022-12-07 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0004_rename_nombremascota_adopcion_nombre_de_mascota_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='encontrados',
            name='mail',
            field=models.EmailField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='encontrados',
            name='telefono',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='provisorios',
            name='mail',
            field=models.EmailField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='provisorios',
            name='telefono',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='provisorios',
            name='tipo',
            field=models.CharField(max_length=40),
        ),
    ]
